name: carte_de_visite_avance
description: une carte de visite.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  google_fonts: ^3.0.0
  carousel_slider: ^4.1.1
  fab_circular_menu: ^1.0.2
  url_launcher: ^6.1.2
  smooth_page_indicator: ^1.0.0+2
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.1.0
  flutter_multi_carousel: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.2.1
  
  
  flutter_lints: ^1.0.0

  

flutter_native_splash:
  




flutter:

  uses-material-design: true

  
  assets:
    - assets/images/

  